### ISSUE TITLE
Running Tests Clarification

### ISSUE THREAD

**Issue by kenwilcox** [exercism/red#71]
I am completely new to Red, but I've been meaning to try it out for some time, so I was happy to see it show up in Exercism!

I was reading the docs here: https://exercism.org/docs/tracks/red/tests which I see is in docs/TESTS.md

It states "Once you get the first test passing, change the _value_ assigned to `ignore-after` word at the beginning of the test script and run it again."

I see that there are tests with `ignore-after` in this project, but the first three that I've downloaded (hello-world, two-fer, and reverse-string) have something like 
`test-init/limit %reverse-string.red 1 ` and no mention of `ignore-after`

Granted this didn't mean anything for the hello-world project.

I figured it out, so it wasn't insurmountable. I'm just wondering if the docs should mention the line in the test script (or show an example)

Thanks for the course, I'm enjoying it so far!

**Comment by dander** [comment]
This is some good feedback, though I think rather than adding clarification to the documentation about how to modify the test script, we should update the tests to not require any modifications. We could have the test scripts take a single argument for `ignore-after`, or give it a named argument if we think there might be more features to add later.
So to run the first 3 tests it could be like
```
red exercise-test.red 3
```

**Comment by kenwilcox** [comment]
I think that is a great idea! That way the test script wouldn’t have to be modified at all.

**Comment by loziniak** [comment]
Addressing this in 78635f46f9 .
